{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('love') as fopen:\n",
    "    data = list(filter(None, fopen.read().split('\\n')))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "34554\n",
      "18091\n"
     ]
    }
   ],
   "source": [
    "print(len(data))\n",
    "data = [s for s in data if len(s.split()) < 20]\n",
    "print(len(data))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from translate_selenium import Translate, run_parallel_in_threads\n",
    "batch_size = 10"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "translators = [Translate('en','ms') for _ in range(batch_size)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  0%|                                        | 0/1810 [00:00<?, ?it/s]Exception in thread Thread-6:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      "  2%|▋                              | 39/1810 [01:05<49:18,  1.67s/it]Exception in thread Thread-398:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:41532\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e770efd0-1005-11e9-996f-2dbdb61fad55/element/:wdc:1546595332602/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      "  4%|█▏                             | 70/1810 [01:57<51:25,  1.77s/it]Exception in thread Thread-705:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:38999\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e325d8a0-1005-11e9-bdab-43433c3f1578/element/:wdc:1546595332618/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      "  6%|█▉                            | 116/1810 [03:18<51:09,  1.81s/it]Exception in thread Thread-1165:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 10%|██▉                           | 175/1810 [05:04<48:32,  1.78s/it]Exception in thread Thread-1760:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 10%|██▉                           | 179/1810 [05:12<51:09,  1.88s/it]Exception in thread Thread-1801:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 11%|███▎                          | 199/1810 [05:48<50:04,  1.86s/it]Exception in thread Thread-2000:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:36522\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ea6be050-1005-11e9-ac55-ef8ffc0ddff9/element/:wdc:1546595332751/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 12%|███▍                          | 209/1810 [06:08<51:22,  1.93s/it]Exception in thread Thread-2099:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60520\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e8e910e0-1005-11e9-b856-d365906c5fba/element/:wdc:1546595332751/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 12%|███▌                          | 213/1810 [06:15<49:49,  1.87s/it]Exception in thread Thread-2141:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:52818\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ec0a7520-1005-11e9-bde9-454fd0b77e12/element/:wdc:1546595332764/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 12%|███▋                          | 223/1810 [06:34<48:06,  1.82s/it]Exception in thread Thread-2236:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:50494\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e4ac0370-1005-11e9-b061-05aa7822f438/element/:wdc:1546595332757/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 14%|████                          | 248/1810 [07:21<48:45,  1.87s/it]Exception in thread Thread-2488:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 14%|████▏                         | 249/1810 [07:23<50:07,  1.93s/it]Exception in thread Thread-2495:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:38999\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e325d8a0-1005-11e9-bdab-43433c3f1578/element/:wdc:1546595332780/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 14%|████▎                         | 257/1810 [07:38<49:15,  1.90s/it]Exception in thread Thread-2582:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 17%|█████▏                        | 310/1810 [09:18<46:58,  1.88s/it]Exception in thread Thread-3107:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44213\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e5db34a0-1005-11e9-9ed4-9720e4b10569/element/:wdc:1546595332826/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 17%|█████▏                        | 315/1810 [09:27<47:21,  1.90s/it]Exception in thread Thread-3162:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 18%|█████▍                        | 326/1810 [09:48<48:21,  1.95s/it]Exception in thread Thread-3272:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44342\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ed7ca2c0-1005-11e9-a052-9570b62672b4/element/:wdc:1546595332877/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 19%|█████▌                        | 335/1810 [10:06<47:25,  1.93s/it]Exception in thread Thread-3355:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 19%|█████▊                        | 350/1810 [10:33<44:00,  1.81s/it]Exception in thread Thread-3512:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44342\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ed7ca2c0-1005-11e9-a052-9570b62672b4/element/:wdc:1546595332897/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 23%|███████                       | 425/1810 [12:57<45:22,  1.97s/it]Exception in thread Thread-4261:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:52818\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ec0a7520-1005-11e9-bde9-454fd0b77e12/element/:wdc:1546595332940/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 28%|████████▍                     | 511/1810 [15:47<43:54,  2.03s/it]Exception in thread Thread-5118:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:41532\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e770efd0-1005-11e9-996f-2dbdb61fad55/element/:wdc:1546595333027/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      "Exception in thread Thread-5115:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:38999\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e325d8a0-1005-11e9-bdab-43433c3f1578/element/:wdc:1546595333018/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      "Exception in thread Thread-5116:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 29%|████████▌                     | 517/1810 [16:00<46:23,  2.15s/it]Exception in thread Thread-5180:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 29%|████████▋                     | 522/1810 [16:10<43:40,  2.03s/it]Exception in thread Thread-5230:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 29%|████████▋                     | 525/1810 [16:17<44:46,  2.09s/it]Exception in thread Thread-5255:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      "Exception in thread Thread-5262:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 32%|█████████▋                    | 582/1810 [18:20<44:57,  2.20s/it]Exception in thread Thread-5829:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60520\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e8e910e0-1005-11e9-b856-d365906c5fba/element/:wdc:1546595333066/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 33%|█████████▉                    | 598/1810 [18:57<47:48,  2.37s/it]Exception in thread Thread-5989:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 34%|██████████                    | 607/1810 [19:17<43:48,  2.19s/it]Exception in thread Thread-6082:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 35%|██████████▋                   | 642/1810 [20:37<49:16,  2.53s/it]Exception in thread Thread-6431:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:52818\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ec0a7520-1005-11e9-bde9-454fd0b77e12/element/:wdc:1546595333137/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 38%|███████████▍                  | 690/1810 [22:32<47:54,  2.57s/it]Exception in thread Thread-6908:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 46%|█████████████▊                | 832/1810 [28:19<40:10,  2.46s/it]Exception in thread Thread-8332:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 46%|█████████████▊                | 836/1810 [28:29<39:48,  2.45s/it]Exception in thread Thread-8367:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44213\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e5db34a0-1005-11e9-9ed4-9720e4b10569/element/:wdc:1546595333293/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 47%|█████████████▉                | 843/1810 [28:46<37:30,  2.33s/it]Exception in thread Thread-8440:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:36522\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ea6be050-1005-11e9-ac55-ef8ffc0ddff9/element/:wdc:1546595333323/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 47%|█████████████▉                | 844/1810 [28:48<38:12,  2.37s/it]Exception in thread Thread-8448:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 50%|███████████████               | 909/1810 [31:37<42:10,  2.81s/it]Exception in thread Thread-9097:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 52%|███████████████▌              | 942/1810 [33:11<42:33,  2.94s/it]Exception in thread Thread-9427:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 53%|███████████████▊              | 955/1810 [33:49<39:58,  2.81s/it]Exception in thread Thread-9556:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:50494\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e4ac0370-1005-11e9-b061-05aa7822f438/element/:wdc:1546595333409/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 54%|████████████████▏             | 975/1810 [34:45<39:58,  2.87s/it]Exception in thread Thread-9761:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 55%|████████████████▎             | 987/1810 [35:20<38:46,  2.83s/it]Exception in thread Thread-9878:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:41532\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e770efd0-1005-11e9-996f-2dbdb61fad55/element/:wdc:1546595333446/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 55%|████████████████             | 1003/1810 [36:05<37:16,  2.77s/it]Exception in thread Thread-10040:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:36522\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ea6be050-1005-11e9-ac55-ef8ffc0ddff9/element/:wdc:1546595333462/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 56%|████████████████▎            | 1017/1810 [36:44<36:44,  2.78s/it]Exception in thread Thread-10175:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:38999\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e325d8a0-1005-11e9-bdab-43433c3f1578/element/:wdc:1546595333464/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 56%|████████████████▎            | 1018/1810 [36:47<37:23,  2.83s/it]Exception in thread Thread-10188:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 57%|████████████████▌            | 1033/1810 [37:31<37:08,  2.87s/it]Exception in thread Thread-10335:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:38999\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e325d8a0-1005-11e9-bdab-43433c3f1578/element/:wdc:1546595333479/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 58%|████████████████▉            | 1055/1810 [38:33<38:46,  3.08s/it]Exception in thread Thread-10560:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:36522\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ea6be050-1005-11e9-ac55-ef8ffc0ddff9/element/:wdc:1546595333507/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 59%|█████████████████▏           | 1069/1810 [39:17<39:46,  3.22s/it]Exception in thread Thread-10700:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:36522\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ea6be050-1005-11e9-ac55-ef8ffc0ddff9/element/:wdc:1546595333520/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 61%|█████████████████▌           | 1098/1810 [40:50<39:49,  3.36s/it]Exception in thread Thread-10989:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 64%|██████████████████▍          | 1151/1810 [43:38<33:55,  3.09s/it]Exception in thread Thread-11521:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:52818\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ec0a7520-1005-11e9-bde9-454fd0b77e12/element/:wdc:1546595333584/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 64%|██████████████████▋          | 1167/1810 [44:29<37:21,  3.49s/it]Exception in thread Thread-11682:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44342\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ed7ca2c0-1005-11e9-a052-9570b62672b4/element/:wdc:1546595333605/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 66%|███████████████████          | 1187/1810 [45:36<34:33,  3.33s/it]Exception in thread Thread-11884:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60642\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/f0930a80-1005-11e9-9e9b-3df24b97f8d0/element/:wdc:1546595333665/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 66%|███████████████████▏         | 1196/1810 [46:06<33:07,  3.24s/it]Exception in thread Thread-11974:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60642\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/f0930a80-1005-11e9-9e9b-3df24b97f8d0/element/:wdc:1546595333672/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 70%|████████████████████▏        | 1259/1810 [49:39<31:07,  3.39s/it]Exception in thread Thread-12604:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60642\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/f0930a80-1005-11e9-9e9b-3df24b97f8d0/element/:wdc:1546595333728/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 71%|████████████████████▍        | 1279/1810 [50:45<28:03,  3.17s/it]Exception in thread Thread-12800:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:36522\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ea6be050-1005-11e9-ac55-ef8ffc0ddff9/element/:wdc:1546595333696/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 71%|████████████████████▋        | 1292/1810 [51:28<29:40,  3.44s/it]Exception in thread Thread-12934:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60642\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/f0930a80-1005-11e9-9e9b-3df24b97f8d0/element/:wdc:1546595333753/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 72%|████████████████████▊        | 1300/1810 [51:55<26:46,  3.15s/it]Exception in thread Thread-13006:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 73%|█████████████████████▏       | 1323/1810 [53:07<24:15,  2.99s/it]Exception in thread Thread-13241:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:52818\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ec0a7520-1005-11e9-bde9-454fd0b77e12/element/:wdc:1546595333731/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 73%|█████████████████████▎       | 1328/1810 [53:24<25:51,  3.22s/it]Exception in thread Thread-13293:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:51703\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ef120fd0-1005-11e9-8199-a38138916578/element/:wdc:1546595333767/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 74%|█████████████████████▌       | 1345/1810 [54:21<24:39,  3.18s/it]Exception in thread Thread-13459:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60520\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e8e910e0-1005-11e9-b856-d365906c5fba/element/:wdc:1546595333727/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 75%|█████████████████████▊       | 1363/1810 [55:21<25:43,  3.45s/it]Exception in thread Thread-13641:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:52818\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ec0a7520-1005-11e9-bde9-454fd0b77e12/element/:wdc:1546595333761/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 75%|█████████████████████▊       | 1365/1810 [55:28<26:05,  3.52s/it]Exception in thread Thread-13661:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 77%|██████████████████████▍      | 1398/1810 [57:29<26:06,  3.80s/it]Exception in thread Thread-13989:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 79%|██████████████████████▊      | 1425/1810 [59:03<20:40,  3.22s/it]Exception in thread Thread-14255:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:38999\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e325d8a0-1005-11e9-bdab-43433c3f1578/element/:wdc:1546595333818/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 79%|██████████████████████▉      | 1434/1810 [59:36<22:44,  3.63s/it]Exception in thread Thread-14346:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:50494\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e4ac0370-1005-11e9-b061-05aa7822f438/element/:wdc:1546595333826/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 80%|█████████████████████▌     | 1446/1810 [1:00:24<24:02,  3.96s/it]Exception in thread Thread-14474:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60642\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/f0930a80-1005-11e9-9e9b-3df24b97f8d0/element/:wdc:1546595333884/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      "Exception in thread Thread-14467:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44213\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e5db34a0-1005-11e9-9ed4-9720e4b10569/element/:wdc:1546595333824/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 81%|█████████████████████▊     | 1459/1810 [1:01:13<23:08,  3.96s/it]Exception in thread Thread-14602:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 81%|█████████████████████▉     | 1471/1810 [1:01:59<21:22,  3.78s/it]Exception in thread Thread-14723:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:51703\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ef120fd0-1005-11e9-8199-a38138916578/element/:wdc:1546595333888/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 84%|██████████████████████▌    | 1512/1810 [1:04:21<17:48,  3.59s/it]Exception in thread Thread-15127:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44213\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e5db34a0-1005-11e9-9ed4-9720e4b10569/element/:wdc:1546595333881/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 84%|██████████████████████▌    | 1515/1810 [1:04:32<17:22,  3.53s/it]Exception in thread Thread-15159:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60520\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e8e910e0-1005-11e9-b856-d365906c5fba/element/:wdc:1546595333871/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 84%|██████████████████████▋    | 1518/1810 [1:04:42<16:21,  3.36s/it]Exception in thread Thread-15192:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44342\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ed7ca2c0-1005-11e9-a052-9570b62672b4/element/:wdc:1546595333904/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 85%|███████████████████████    | 1545/1810 [1:06:20<16:52,  3.82s/it]Exception in thread Thread-15464:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60642\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/f0930a80-1005-11e9-9e9b-3df24b97f8d0/element/:wdc:1546595333964/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 86%|███████████████████████▏   | 1554/1810 [1:06:51<15:12,  3.56s/it]Exception in thread Thread-15553:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:51703\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ef120fd0-1005-11e9-8199-a38138916578/element/:wdc:1546595333957/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 86%|███████████████████████▎   | 1560/1810 [1:07:14<16:03,  3.85s/it]Exception in thread Thread-15613:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:51703\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/ef120fd0-1005-11e9-8199-a38138916578/element/:wdc:1546595333961/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      "Exception in thread Thread-15607:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 87%|███████████████████████▍   | 1570/1810 [1:07:52<15:15,  3.81s/it]Exception in thread Thread-15708:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:41532\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e770efd0-1005-11e9-996f-2dbdb61fad55/element/:wdc:1546595333948/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 87%|███████████████████████▍   | 1574/1810 [1:08:08<14:49,  3.77s/it]Exception in thread Thread-15746:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:50494\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e4ac0370-1005-11e9-b061-05aa7822f438/element/:wdc:1546595333947/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 87%|███████████████████████▌   | 1580/1810 [1:08:30<14:08,  3.69s/it]Exception in thread Thread-15814:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 87%|███████████████████████▌   | 1581/1810 [1:08:34<14:31,  3.80s/it]Exception in thread Thread-15821:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 88%|███████████████████████▋   | 1585/1810 [1:08:49<13:41,  3.65s/it]Exception in thread Thread-15858:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:41532\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e770efd0-1005-11e9-996f-2dbdb61fad55/element/:wdc:1546595333960/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 89%|███████████████████████▉   | 1607/1810 [1:10:09<11:56,  3.53s/it]Exception in thread Thread-16079:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60520\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e8e910e0-1005-11e9-b856-d365906c5fba/element/:wdc:1546595333951/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 90%|████████████████████████▎  | 1630/1810 [1:11:35<12:12,  4.07s/it]Exception in thread Thread-16307:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 91%|████████████████████████▋  | 1651/1810 [1:12:55<09:28,  3.57s/it]Exception in thread Thread-16522:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 94%|█████████████████████████▎ | 1699/1810 [1:15:55<07:11,  3.89s/it]Exception in thread Thread-16997:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44213\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e5db34a0-1005-11e9-9ed4-9720e4b10569/element/:wdc:1546595334042/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 95%|█████████████████████████▌ | 1715/1810 [1:16:57<05:57,  3.76s/it]Exception in thread Thread-17164:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60642\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/f0930a80-1005-11e9-9e9b-3df24b97f8d0/element/:wdc:1546595334118/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 95%|█████████████████████████▋ | 1719/1810 [1:17:13<06:10,  4.07s/it]Exception in thread Thread-17195:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:38999\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e325d8a0-1005-11e9-bdab-43433c3f1578/element/:wdc:1546595334067/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 96%|█████████████████████████▊ | 1732/1810 [1:18:03<05:16,  4.06s/it]Exception in thread Thread-17327:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      " 97%|██████████████████████████ | 1748/1810 [1:19:01<03:41,  3.58s/it]Exception in thread Thread-17494:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:60642\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/f0930a80-1005-11e9-9e9b-3df24b97f8d0/element/:wdc:1546595334146/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 97%|██████████████████████████▏| 1755/1810 [1:19:28<03:25,  3.74s/it]Exception in thread Thread-17555:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:38999\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e325d8a0-1005-11e9-bdab-43433c3f1578/element/:wdc:1546595334099/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 98%|██████████████████████████▌| 1779/1810 [1:21:02<01:49,  3.54s/it]Exception in thread Thread-17797:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in translate\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 23, in <listcomp>\n",
      "    text = [elem.text for elem in self.driver.find_elements_by_xpath(span)]\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 76, in text\n",
      "    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.StaleElementReferenceException: Message: {\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Accept\":\"application/json\",\"Accept-Encoding\":\"identity\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"127.0.0.1:44213\",\"User-Agent\":\"selenium/3.141.0 (python linux)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/e5db34a0-1005-11e9-9ed4-9720e4b10569/element/:wdc:1546595334108/text\"}}\n",
      "Screenshot: available via screen\n",
      "\n",
      "\n",
      " 98%|██████████████████████████▌| 1780/1810 [1:21:05<01:49,  3.64s/it]Exception in thread Thread-17811:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████████████████████▉| 1805/1810 [1:22:17<00:12,  2.60s/it]Exception in thread Thread-18058:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/threading.py\", line 862, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 34, in task_wrapper\n",
      "    result.put(target(*args))\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 27, in task_translate\n",
      "    return translator.translate(string)\n",
      "  File \"/home/husein/space/translation/translate_selenium.py\", line 24, in translate\n",
      "    return text[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      "100%|███████████████████████████| 1810/1810 [1:22:30<00:00,  2.31s/it]\n"
     ]
    }
   ],
   "source": [
    "from tqdm import tqdm\n",
    "translated = []\n",
    "for no in tqdm(range(0, len(data), batch_size), ncols=70):\n",
    "    strings = data[no: no + batch_size]\n",
    "    combined = [(translators[i],strings[i],) for i in range(len(strings))]\n",
    "    translated.extend(run_parallel_in_threads(combined))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('translated-love', 'w') as fopen:\n",
    "    fopen.write('\\n'.join(translated))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "15232"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(translated)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
